<a href="https://colab.research.google.com/github/UknowYunmo/Image-Processing/blob/main/01-numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
list_data=[1,2,3]
print(list_data)

import numpy as np
array=np.array(list_data)
print(array)
print(array.size)
print(array.dtype)
print(array[1])

[1, 2, 3]
[1 2 3]
3
int64
2


In [3]:
array1=np.arange(4)
print(array1)

array2=np.zeros((4,4),dtype=int)
print(array2)

array3=np.zeros((4,4),dtype=float)
print(array3)

array4=np.random.randint(0,10,(3,3)) # 0부터 9까지 3x3 배열로 생성
print(array4)

array5=np.random.normal(0,1,(3,3)) # 평균이 0이고, 표준편차가 1인 표준 정규분포를 따르는 3x3 배열 생성
print(array5)

[0 1 2 3]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 2 0]
 [6 1 6]
 [9 4 6]]
[[-0.48012254 -1.05344922 -1.18182318]
 [-1.19950411  1.05173746 -1.46090864]
 [ 0.10701082  1.51959596  0.52172423]]


In [16]:
array1=np.array([1,2,3,4])
array2=array1.reshape((2,2)) # 행열 변환
print(array2)

array1=np.array([1,2,3])
array2=np.array([4,5,6])
array3=np.concatenate([array1,array2]) # 위 아래로 붙이기
print(array3)
print(array3.shape)

array1=np.arange(8).reshape(2,4) # 0~7을 쭉 쓰고, 2x4로 변환
print(array1)
array2=np.arange(4).reshape(1,4)
print(array2)
array3=np.concatenate([array1,array2],axis=0) # 위 아래로 붙이기
print(array3)

array1=np.arange(8).reshape(2,4)
print(array1)
left,right=np.split(array1,[3],axis=1) # 열 기준 3번째를 기준으로 행열 나누기, axis=0 -> 행 기준
print(left.shape)
print(right.shape)
print(left)
print(right)

[[1 2]
 [3 4]]
[1 2 3 4 5 6]
(6,)
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
(2, 3)
(2, 1)
[[0 1 2]
 [4 5 6]]
[[3]
 [7]]


배열과 상수끼리 연산이 이루어지면 모든 요소에 동일한 연산이 수행된다. 이 때 상수를 스칼라 값이라 한다.

In [20]:
array=np.random.randint(1,10,size=4)
print(array)
array=array.reshape(2,2)
print(array)

result=array+10
print(result)

result=array*2
print(result)

[2 8 1 8]
[[2 8]
 [1 8]]
[[12 18]
 [11 18]]
[[ 4 16]
 [ 2 16]]


서로 다른 형태의 배열을 연산할 때는 행 우선으로 수행된다. 이것을 브로드캐스팅이라 한다.

브로드캐스트 : 형태가 다른 배열을 연산할 수 있도록 배열의 형태를 동적으로 변환

해보니까 행,열 중 둘 중 하나는 맞아떨어져야 브로드캐스팅이 되고 둘 다 다르면 오류가 발생한다.

In [31]:
array1=np.arange(4).reshape(2,2) #(2x2)
array2=np.arange(2) #(1x2)
print(array1,array2)

array3=array1+array2
print(array3)

array1=np.arange(0,16).reshape(4,4)
array2=np.arange(0,4).reshape(4,1)
print(array1)
print(array2)
print(array1+array2)

[[0 1]
 [2 3]] [0 1]
[[0 2]
 [2 4]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]]


마스킹 연산 : 행열의 각 원소에 대해 조건에 따라 체크한다

이를 활용하면, 요소별로 조건을 체크해서 비교하지 않고 한 번에 처리할 수 있다

In [66]:
array1=np.arange(16).reshape(4,4)
print(array1)

array2=array1<10
print(array2)

print(array2[1,:]) # 1열 슬라이싱
print(array2[:,1]) # 1행 슬라이싱

array1[array2]=100 # 10보다 큰 요소 값만 100으로 변환
print(array1)

# 집계 함수
print(np.max(array1))
print(np.min(array1))
print(np.sum(array1))
print(np.mean(array1))

print(np.sum(array1,axis=0)) # 행별로 집계함수도 가능

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[ True  True  True  True]
[ True  True  True False]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]
100
10
1075
67.1875
[312 313 224 226]


배열을 파일로 저장할 수도 있고, 복합 배열도 저장할 수 있다.

인덱싱으로 불러올 수 있는데, 아직 인덱싱할 때 이름을 호출하는 방법은 찾을 수 없었다. 그러니 복합 배열을 저장할 때는 파일명에 인덱싱할 때 쓸 이름을 같이 넣거나 통일시키는 게 좋을 거 같다.

In [75]:
array=np.arange(0,10)
np.save('saved.npy',array) # 해당 배열을 'saved.npy'라는 파일로 저장

result=np.load('saved.npy')
print(result)

array1=np.arange(0,10)
array2=np.arange(10,20)
np.savez('saved.npz',saved_array1=array1,saved_array2=array2)
data=np.load('saved.npz')
print(data)
print(data['saved_array1'])
print(data['saved_array2'])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [ ]:
concatenate 연습 중에 좀 이상한걸 발견했다.
위 예시의 경우 axis=0으로 했는데 위아래로 안 붙고 계속 옆으로 붙는다.

In [104]:
array1=np.array([5,9,10,3,1])
array2=np.array([5,9,10,3,1])
array3=np.concatenate([array1,array2],axis=0)
print(array3)

[ 5  9 10  3  1  5  9 10  3  1]


아무리 찾아봐도 맞는데 출력은 이렇게 되서, hstack과 vstack을 알게 되었다.

hstack : 옆으로 붙이기

vstack : 위아래로 붙이기

In [106]:
array1=np.array([5,9,10,3,1])
array2=np.array([5,9,10,3,1])
array3=np.vstack([array1,array2]) # 위아래
print(array3)
print()
array3=np.hstack([array1,array2]) # 옆
print(array3)

[[ 5  9 10  3  1]
 [ 5  9 10  3  1]]

[ 5  9 10  3  1  5  9 10  3  1]


정렬도 가능. 또한 axis 값으로 행열 별로도 가능.

In [108]:
array=np.array([5,9,10,3,1])
array.sort() # 정렬
print(array)
print(array[::-1]) # 내림차순

array=np.array([[5,9,10,3,1],[8,3,4,2,5]])
print(array)
array.sort(axis=0)
print(array)

[ 1  3  5  9 10]
[10  9  5  3  1]
[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


균일한 간격으로 데이터를 생성할 수도 있고, 시드 값을 설정할 수도 있다.

In [110]:
array=np.linspace(0,10,5) # 0부터 10까지 동일한 간격으로 5개 요소를 만들어라
print(array)

np.random.seed(7) # 랜덤 고정
print(np.random.randint(0,10,(2,3)))

[ 0.   2.5  5.   7.5 10. ]
[[4 9 6]
 [3 3 7]]


numpy를 =으로 복사하면 복사한 곳의 요소를 수정했을 때 원본까지 같이 수정이 된다 ( 깊은 복사 ㅠㅠ )
이러한 사태를 막기 위해 복사할 때는 copy()를 써야한다.

In [123]:
array1=np.arange(0,10)
array2=array1
array2[0]=99
print(array1)

array3=array1.copy()
array3[0]=999
print(array1) # 99 그대로

[99  1  2  3  4  5  6  7  8  9]
[99  1  2  3  4  5  6  7  8  9]
